# Generated by Django 4.1.7 on 2023-04-01 06:34

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_blogpost_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='participants',
            field=models.ManyToManyField(related_name='blog_participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
